# Machine Learning

Machine learning is the science (and art) of programming computers so they can learn from data. 

For example:
- Ranking your web search result (Google)
- Recommendation system: Amazon
- AlphaGo
- Chatgpt or Large Language Model (Large Language Model)
- Spam filter
- Image classification
- Detecting credit card fraud
- ...

In general, we hope to use previous data to design(train) some algorithms(model), then use trained models to predict when we receive new data.

- Example 1: We can use emails (data) to construct a spam filter (algorithm, model), then we can use spam filter to predict that new emails (new data) is a spam or not.

- Example 2: We can use your current friends list (data) to construct a friend recommendation system (algorithm, model), then we can use this model to find people (new data) who you may know.

- ...

**So, our goal is to finding a model that can be used on unseen data**.


## Supervised and Unsupervised learning

Supervised learning means that you can use both input $x$ and output $y$ to train a model. The output $y$ is also called *labels*.

If the labels are "continuous" real numbers (e.g. stock price, house price, insurance fee, height, weights, and etc ), then it is **regression problem**.

If the labels are discrete categories (e.g. dog vs cat, True vs False, handwritten digits numbers(0-9), 0 vs 1, or -1 vs 1, and etc), then it is **classification problem**.


We will also discuss unsupervised learning problem where labels $y$ is not available. Two typical unsupervised learning problems are **clustering** and **dimension reduction**.


## Machine Learning pipeline:

1. Look at the Big Picture:
    
    - You should understand your task, e.g regression (predict housing price) or classification (handwritten numbers).
    - Select a performance measure
    - ...

2. Get the Data

    - Download the data from internet
    - ...

3. Discover your data and visualize your data

    - Pandas and Matplotlib
    - ...

4. Prepare your data for Machine Learning Algorithm

    - Algorithm only accepts numeric values
    - Data cleaning (fillna, dropna)
    - Text and categorical attributes to numerics
    - ...

5. Select and train your model


6. Fine-tune your model

    - Cross-validation
    - try different models and ensemble them
    - evaluate your model on test set

7. Launch, monitor, and maintain your model

# Regression

Let's start with regression problem where we will construct several machine learning models to predict insurance charges.

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, LabelEncoder

from sklearn.linear_model import LinearRegression

import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
url = 'https://raw.githubusercontent.com/liaochunyang/PIC16/refs/heads/main/PIC16B/04_ML/insurance.csv'
df = pd.read_csv(url)
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

# Goal

The goal here is to construct machine learning models to successfully predict 'charges'?

The problems that I am interested in (Problem statement) are

- What are the most important features?
- How can I improve model performance?
- What is the best model? And what is the best accuracy I can obtain?
- How can I inteprate my result?
- Does data analysis help model construction?
- ...

# Encoding:

Encoding means transforming categorical features to numerical features.

- One-hot encoding: each category is represented by a binary/sparse vector, and each category becomes to a new column.

- Label encoding: integer representation. Each category is represented by an integer.

In [3]:
# Two functions to do encodings.
def one_hot(df, cols):
    """
    df: pandas DataFrame
    param: cols a list of columns to encode 
    return a DataFrame with one-hot encoding
    """
    for each in cols:
        dummies = pd.get_dummies(df[each], prefix=each, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
    return df


def label(df, cols):
    
    df_new = df.copy()
    
    for each in cols:
        
        label_encoder = LabelEncoder()
        #dummies = label_encoder.fit_transform(df[each])
        #dummies = pd.DataFrame(dummies, columns=[each])
        #df = pd.concat([df, dummies], axis=1)
        
        label_encoder = LabelEncoder()
        df_new[each] = label_encoder.fit_transform(df_new[each])
        
    return df_new

In [4]:
# use one-hot encoding

,age,sex,bmi,children,smoker,region,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,female,27.900,0,yes,southwest,16884.92400,1,0,0,1,0,0,0,1
1,18,male,33.770,1,no,southeast,1725.55230,0,1,1,0,0,0,1,0
2,28,male,33.000,3,no,southeast,4449.46200,0,1,1,0,0,0,1,0
3,33,male,22.705,0,no,northwest,21984.47061,0,1,1,0,0,1,0,0
4,32,male,28.880,0,no,northwest,3866.85520,0,1,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,0,1,1,0,0,1,0,0
1334,18,female,31.920,0,no,northeast,2205.98080,1,0,1,0,1,0,0,0
1335,18,female,36.850,0,no,southeast,1629.83350,1,0,1,0,0,0,1,0
1336,21,female,25.800,0,no,southwest,2007.94500,1,0,1,0,0,0,0,1
1337,61,female,29.070,0,yes,northwest,29141.36030,1,0,0,1,0,1,0,0

In [5]:
# use label encoding

      age  sex     bmi  children  smoker  region      charges
0      19    0  27.900         0       1       3  16884.92400
1      18    1  33.770         1       0       2   1725.55230
2      28    1  33.000         3       0       2   4449.46200
3      33    1  22.705         0       0       1  21984.47061
4      32    1  28.880         0       0       1   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    1  30.970         3       0       1  10600.54830
1334   18    0  31.920         0       0       0   2205.98080
1335   18    0  36.850         0       0       2   1629.83350
1336   21    0  25.800         0       0       3   2007.94500
1337   61    0  29.070         0       1       1  29141.36030

[1338 rows x 7 columns]

# Linear Regression model

Linear regression model describes the relationship between features and targets using straight line (2D) or linear hyperplane (high-dimensional), see the following picture:

![Linear_least_squares_example2.svg](https://community.cloudera.com/t5/image/serverpage/image-id/25068iFF075A5AEC3B8528/image-size/medium?v=v2&px=400)


**Fact: A straight line can be modeled as y=kx+b where k is called slope and b is called intercept.**

Our goal is to find $k$ and $b$ such that the obtained straight line fits your data well (how to define this mathematically?)


**Formula:**

We set up the following minimization problem

$$\mathop{\mathbf{minimize}}_{k,b} \frac{1}{m}\sum_{i=1}^{m} (kx^{(i)} + b - y_i)^2, $$
where m is the number of data samples.

**High-dimensional case:**

In many real world applications, you are asked to use more than one features to predict the output, see example below.

In high dimension case, the linear regression model can be written as $w_0 + w_1x_1 + ... + w_dx_d$, where $d$ is the dimension of the inputs data $x$, i.e. $x=(x_1, x_2, ..., x_d)\in\mathbb{R}^d$. Our goal is to find coefficients $w_0, ..., w_d$.

Given training samples $\{x^{(i)}, y^{(i)}\}_{i=1}^m$, finding coefficients is done by solving the following optimization problem

$$ \frac{1}{m} \sum_{i=1}^m (w_0 + w_1x^{(i)}_1 + ... + w_dx^{(i)}_d - y^{(i)})^2. $$

**Training machine learning models:**

Usually, training machine learning models is equivalent to solving an optimization problem.

# Baseline

In this model, we will use six features to predict the target. I do not have any data analysis and data process, therefore it should be the worst model.

In the future, I will compare other models with the baseline, which shows that how we can improve the model performance. 


### Train test split

Train test split is the most important step. Remember that our goal is to create a model such that it can be generalized to unseen data set. So, we need to use some data samples to train a model, and then use unseen samples to test the performance. In other words, when you test the model performance, you cannot use training samples. Moreover, it is easy to design some trivial models that performs well on training data set but fail to work on new data points. This phenomenon is called **overfitting**.

In [ ]:
# Let's use label-encoding

In [7]:

print(f'Relative error is {rel*100:.2f}%')

-481.6926861118791 [   257.80293688    338.23344342    394.89440954     50.03306263
    -50.03306263 -12003.1807562   12003.1807562     490.93876054
    196.20508782   -433.74510457   -253.3987438 ]
MSE is 34940858.92950
Relative error is 0.42
Relative error is 41.76%

#### Some mathematics

**Mean-squared error (MSE)**: $\frac{1}{m}\sum_{i=1}^m (\hat{y}_i-y_i)^2$, where 
- $\hat{y}_i$ is the i-th predicted value by your model. 
- $y_i$ is the i-th true value from your dataset.
- It computes training MSE if y_i are training outputs and $\hat{y}$ are computed by training inputs.
- We can also compute test MSE when we use test samples.

When we compare models, we use **Test MSE** because we want to measure the model performance on the unseen dataset.

Test mean-squared error: good for comparing models, no interpretation. When we choose models, we prefer small mean-squared error.

**Relative error** measures how large your mistake is as a fraction of the true value, the math formula is
$$ \frac{error}{True Value} $$

For multiple test samples, we define the **average relative test error** as
$$ \frac{1}{m}\sum_{i=1}^m \frac{|y_i-\hat{y}_i| }{|y_i|}$$

# Data Analysis and Feature Selection Can Improve Model Performance

In this section, we show that data analysis and feature selection can improve model performance. Recall PIC16A notes, we did a detailed data analysis and observed that 

- smoker is an important feature when we predict charges because the average charges of two groups are different.
- In the smoker group, I observe a strong linear relation between bmi and charges.
- for non-smoker group, bmi is not a key factor in determining the charges, but age is important.

In the following code, my machine learning model looks like:

$$ \hat{y} = w_0 + w_1 * age + w_2 * smoker + w_3 * bmi * smoker $$

-1927.9059861764417 [   263.98433743 -20467.76538266   1446.67217802]
MSE is 19270991.19385
Relative error is 0.32
Relative error is 32.42%

In the following code, my machine learning model looks like:

$$ \hat{y} = w_0 + w_1 * age + w_2 * smoker + w_3 * bmi * smoker + w_4 * age * (1-smoker) $$

-1881.1763898254794 [ 2.65219493e+02 -2.15564188e+04  1.46589452e+03 -5.83891830e+00]
MSE is 35457453.30454
Relative error is 0.29
Relative error is 29.20%

# Can we further improve the model performance?

I will do **log transformation** for my targets.

#### Why log-transformation?

The target is skewed: most samples have small values, while there are some extremely large quantities. If we do not apply any transformation, then the training algorithm will focus more on large quantities, which causes bias in the training process. 

We can use log transformation to address the problem.

7.302142910309572 [0.41044218 1.35629979 2.5069501  2.11025728]
MSE is 24709907.03438
Relative error is 0.20
Relative error is 20.44%

7.398773322991449 [0.56438144 1.41292676 2.11664152 1.83935612]
MSE is 24996157.43905
Relative error is 0.21
Relative error is 21.05%

7.843420327653558 [1.121462   1.33733107 0.98121776 0.71401897]
MSE is 38709207.03226
Relative error is 0.25
Relative error is 24.63%

MSE is 16594265.25533
Relative error is 0.18
Relative error is 17.77%

In [ ]:
#####################  Linear Regression

In [ ]:
######################### Ridge Regression

In [ ]:
######################## LASSO

In [ ]:
###################### Random Forest
from sklearn.ensemble import RandomForestRegressor

# Regularization

Regualization was proposed to reduce model complexity. It prevents **overfitting** by adding a penalty term to the cost function, discouraging overly complex models.

**Overfitting:** the model has perfect performance on training samples, but fails to generalize to any unseen samples.

In the classical machine learning theory, people showed that overfitting is harmful. In recent years, people realize that overfitting can be benign under some certain conditions. Understanding the benign overfitting mechanism is an active research area. 


## Ridge Regression and Least Absolute Shrinkage and Selection Operator (LASSO)


Please see this review for the details:[Lasso and Ridge regression: a comprehensive review of applications
and developments in machine learning](https://link.springer.com/article/10.1007/s41060-025-00957-y)

#### Ridge Regression:

Ridge Regression solves the following optimization problem:

$$ \frac{1}{m} \sum_{i=1}^m (w_0 + w_1x^{(i)}_1 + ... + w_dx^{(i)}_d - y^{(i)})^2 + \lambda \sum_{j=1}^d w_d^2,$$

where $\lambda$ is a regularization parameter. 

#### LASSO:

LASSO solves the following optimization problem:


$$ \frac{1}{m} \sum_{i=1}^m (w_0 + w_1x^{(i)}_1 + ... + w_dx^{(i)}_d - y^{(i)})^2 + \lambda \sum_{j=1}^d |w_d|,$$

where $\lambda$ is a regularization parameter. 

#### Difference:

LASSO can produce sparse coefficients.

#### The role of regularization parameter:

Larger $\lambda$ means stronger regularization, since it focuses more on the regularization term (the second term). When $\lambda\to0$, the training algorithm forces the model to memorize the traning samples, which leads to overfitting.

## Repeat Experiments to remove randomness

Notice that train-test split will create training and testing samples randomly. Different training samples may results in different models, and hence we should repeat our experiments to remove the effect of randomness.

In [24]:
def compute_test_error(X, y):
    """
    Compute test error. 
    Args:
    X: numpy array containing all features.
    y: target. A numpy array.
    Returns:
    mse: mean squared error.
    rel_se: relative squared error.
    """
    # train test split: each time you will randomly select training and test samples.
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)
    
    # model initialization
    model = LinearRegression()
    # trianing this model
    model.fit(X_train, y_train)
    
    # prediction 
    y_pred = model.predict(X_test)
    
    # compute the relative squared error
    rel = np.mean( np.abs(y_test-y_pred)/np.abs(y_test) )
    
    return rel

Relative Test Error is 0.43 with standard deviation 0.04

Relative Test Error is 0.32 with standard deviation 0.03

# Other directions to explore

To further improve the model performance, we could explore the following:

- More features analysis: bmi * age, age ** 2, ...
- Label encoding vs one-hot-encoding
- Tune hyper-parameters: cross-validation
- Try different models: XGBoost, Neural Network, ...
- We have observed that feature 'smoker' is the most important features, therefore we could construct two models.
- We can ensemble machine learning models, see the next code. We will come back to ensemble models later.
- ...

In [170]:
from sklearn.ensemble import VotingRegressor, RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression


# apply label encoding
df_med = label(df, cat_all)
# Model 1: three features to predict "age", "smoker", "bmi"*"smoker"
df_med['A'] = df_med['bmi'] * df_med['smoker']
df_med1 = df_med.drop(columns = ['sex', 'children', 'region', 'bmi'])

# Dataset X, y
X = df_med1[['age','smoker','A']].to_numpy()
y = df_med1['charges'].to_numpy()


T = 20
rel = []
for i in range(T):

    # train_test_split
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.1)

    # Define base models
    reg1 = GradientBoostingRegressor()
    reg2 = RandomForestRegressor()
    reg3 = LinearRegression()

    # Create the ensemble
    eregr = VotingRegressor(estimators=[('gb', reg1), ('rf', reg2), ('lr', reg3)])
    eregr.fit(X_train, np.log(y_train) )

    y_pred = eregr.predict(X_test)

    rel.append( np.mean( np.abs(y_test-np.exp(y_pred))/np.abs(y_test) ) )
    
rel = np.array(rel)
print(f'Relative Test Error is {np.mean(rel):.2f} with standard deviation {np.std(rel):.2f} ')

Relative Test Error is 0.21 with standard deviation 0.02

# Coding Style:

You may observe that the machine learning pipeline has data processing + model construction + prediction/testing. Therefore, it is natural to split your code to several blocks. Moreover, you can write functions and classes to reduce code repetition and clean your code.